### ISSUE TITLE
Duplicate notification sounds

### ISSUE THREAD

**Issue by jansol** [krisak/vector-electron-desktop#2]
When receiving a notification, vector plays its own notification sound, followed by the OS playing its sound for desktop notifications. Maybe sound notifications should be disabled on desktop notifications.

**Comment by iskrisis** [comment]
Which platform? Osx El-Capitan not doing that for me. Are you sure you dont have the same metrix server opened in a vector browser?

**Comment by jansol** [comment]
Looks like it was indeed safari being slow to stop receiving notifications. At least it didn't happen anymore today...

**Comment by jansol** [comment]
Nevermind, now it happened again. Try activating a different window and moving it in front of vector, then getting a notification seems to trigger two sounds.

**Comment by jansol** [comment]
closing as obsolete
