### ISSUE TITLE
Image preview layout is wonky

### ISSUE THREAD

**Issue by jansol** [krisak/vector-electron-desktop#3]
When clicking an image to see its large preview, the close button and metadata end up at their usual height, but near the center of the window, covering the center and top-center of the image even when the window would be large enough to keep them out of the image.

**Comment by iskrisis** [comment]
What do you mean? Can you post screenshot? I cant reproduce it.

This sounds like vector bug. The only thing i had to implement was opening regular browser when you click download image.

**Comment by jansol** [comment]
Example:
![screen shot 2016-07-26 at 23 11 59](https://cloud.githubusercontent.com/assets/2588851/17154729/f3d48bf4-538a-11e6-88ee-e0a4e58331cb.png)

Note how the metadata box and the title are right in the center of the image. (the X for closing it is not in the corner where it should be either)

**Comment by iskrisis** [comment]
That is strange. I have no idea what it could be since these are just react components and i am not touching it at all. It should be no differend than if you would use vector in chromium.

**Comment by jansol** [comment]
closing as obsolete
