### ISSUE TITLE
Allow self-updating?

### ISSUE THREAD

**Issue by jansol** [krisak/vector-electron-desktop#5]
Vector-web now has a fancy changelog dialog when it notices a new version on the server. It would likely make sense to use that for the packaged version too. Ideally extend it to also show changes to the electron packaging and maybe electron itself?

**Comment by iskrisis** [comment]
Sorry start of the school year and i am pretty busy. 

Anyways i think there is a lot to be desired from the desktop auto-update.

**Comment by jansol** [comment]
riot-desktop supercedes this and supports sel-updating so closing this
